name: "Build and Test"
on:
  schedule:
    # minute (0 - 59) | hour (0 - 23) | day of the month (1 - 31) | month (1 - 12 or JAN-DEC) | day of the week (0 - 6 or SUN-SAT)
    - cron: '5 2 * * *'
  push:
  workflow_dispatch:

jobs:
  jobOne:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build and test the project
        run: cd threadload && chmod +x gradlew && ./gradlew --warning-mode all test jar 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
